version: '3'
services:
  django:
    build:
      context: backend
      dockerfile: Dockerfile
    image: skillwell/backend
    container_name: django_skillwell
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresql
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - postgresql
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8088
  react:
    build:
      context: skillwell-frontend
      dockerfile: Dockerfile
    image: skillwell/frontend
    container_name: react_skillwell
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    command: npm run dev
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql_skillwell
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=$DB_USER
      - POSTGRESQL_PASSWORD=$DB_PASSWORD
      - POSTGRESQL_DATABASE=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: