const JobsInfo = [
  {
    id: 0,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    category: "Web Development",
    title: "Web Developer",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "M22YT020",
    creator: "Tanmay Bhat",
  },
  {
    id: 1,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    category: "Video Editing",
    title: "Video Editor",
    jobTime: "Part-time",
    jobLocation: "Remote",
    rollNo: "B21CS001",
    creator: "Samay Raina",
  },
  {
    id: 2,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    category: "App Development",
    title: "App Developer",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "P22EE054",
    creator: "Samay Raina",
  },
  // {
  //   id: 3,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "Graphic Design",
  //   jobTime: "Part-time",
  //   jobLocation: "On site",
  //   rollNo: "50,000 - 55,000",
  //   creator: "MC Stan",
  // },
  // {
  //   id: 4,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "Poster Design",
  //   jobTime: "Full-time",
  //   jobLocation: "Remote",
  //   rollNo: "30,000 - 40,000",
  //   creator: "Tanmay Bhat",
  // },
  // {
  //   id: 5,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "Machine Learning",
  //   jobTime: "Full-time",
  //   jobLocation: "Remote",
  //   rollNo: "70,000 - 80,000",
  //   creator: "Shantnu Chaudhry",
  // },
  // {
  //   id: 6,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "Video Editing",
  //   jobTime: "Full-time",
  //   jobLocation: "Remote",
  //   rollNo: "45,000 - 50,000",
  //   creator: "Shantnu Chaudhry",
  // },
  // {
  //   id: 7,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "App Development",
  //   jobTime: "Full-time",
  //   jobLocation: "Remote",
  //   rollNo: "25,000 - 35,000",
  //   creator: "Samay Raina",
  // },
  // {
  //   id: 8,
  //   image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
  //   category: "Graphic Design",
  //   jobTime: "Full-time",
  //   jobLocation: "On site",
  //   rollNo: "40,000 - 45,000",
  //   creator: "Video Editing",
  // },
];

export default JobsInfo;
