const JobsInfo = [
  {
    id: 0,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Web Development",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "75,000 - 90,000",
    creator: "Tanmay Bhat",
  },
  {
    id: 1,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Video Editing",
    jobTime: "Part-time",
    jobLocation: "Remote",
    rollNo: "55,000 - 70,000",
    creator: "Samay Raina",
  },
  {
    id: 2,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "App Development",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "60,000 - 70,000",
    creator: "Samay Raina",
  },
  {
    id: 3,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Graphic Design",
    jobTime: "Part-time",
    jobLocation: "On site",
    rollNo: "50,000 - 55,000",
    creator: "MC Stan",
  },
  {
    id: 4,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Poster Design",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "30,000 - 40,000",
    creator: "Tanmay Bhat",
  },
  {
    id: 5,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Machine Learning",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "70,000 - 80,000",
    creator: "Shantnu Chaudhry",
  },
  {
    id: 6,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Video Editing",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "45,000 - 50,000",
    creator: "Shantnu Chaudhry",
  },
  {
    id: 7,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "App Development",
    jobTime: "Full-time",
    jobLocation: "Remote",
    rollNo: "25,000 - 35,000",
    creator: "Samay Raina",
  },
  {
    id: 8,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    title: "Graphic Design",
    jobTime: "Full-time",
    jobLocation: "On site",
    rollNo: "40,000 - 45,000",
    creator: "Video Editing",
  },
];

export default JobsInfo;
