const JobsInfo = [
  {
    id: 0,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "YouTube Producer",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "75,000 - 90,000",
    name: "Tanmay Bhat",
  },
  {
    id: 1,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Video Editor",
    jobTime: "Part-time",
    jobLocation: "Remote",
    jobAmout: "55,000 - 70,000",
    name: "Samay Raina",
  },
  {
    id: 2,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "YouTube Strategist",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "60,000 - 70,000",
    name: "Samay Raina",
  },
  {
    id: 3,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Creative Director",
    jobTime: "Part-time",
    jobLocation: "On site",
    jobAmout: "50,000 - 55,000",
    name: "MC Stan",
  },
  {
    id: 4,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Thumbnail Designer",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "30,000 - 40,000",
    name: "Tanmay Bhat",
  },
  {
    id: 5,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Channel Manager",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "70,000 - 80,000",
    name: "Shantnu Chaudhry",
  },
  {
    id: 6,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Video Editor",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "45,000 - 50,000",
    name: "Shantnu Chaudhry",
  },
  {
    id: 7,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Script Writer",
    jobTime: "Full-time",
    jobLocation: "Remote",
    jobAmout: "25,000 - 35,000",
    name: "Samay Raina",
  },
  {
    id: 8,
    image: "https://www.iisermohali.ac.in/images/faculty/prasad.jpg",
    jobTitle: "Creative Director",
    jobTime: "Full-time",
    jobLocation: "On site",
    jobAmout: "40,000 - 45,000",
    name: "Video Editor",
  },
];

export default JobsInfo;
