name: Deploy to GCE

on:
  push:
    branches:
      - deploy

env:
  # Set the GCP project to deploy to
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  INSTANCE_NAME: ${{ secrets.GCP_INSTANCE_NAME }}
  ZONE: ${{ secrets.GCP_ZONE }}
  # Set the GCP service account key
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: $PROJECT_ID
          service_account_key: $GCP_SA_KEY
          export_default_credentials: true

      - name: Deploy to GCE
        run: |
          # Your deployment script or commands go here
          # e.g., scp, rsync, or any other deployment method

          # Example: Copy files to GCE using gcloud compute scp
          gcloud compute scp --zone=$ZONE --recurse ./your-app/* $INSTANCE_NAME:/var/www/html

          # Restart your application or any other necessary steps

      - name: Build Docker Container
        run: |
          gcloud compute ssh --zone=your-instance-zone your-instance-name --command "cd skillwell && cp .env.example .env && sudo docker-compose up -d --build"

# Add any additional steps or adjustments based on your deployment process.
